name: "Build and test"
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies via pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
          version: 7
          run_install: false
          

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install && cd web && pnpm install
    
    - name: Pnpm test
      run: pnpm test

    - name: Pnpm build
      run: pnpm test