name: "Build and test"
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v1

    - name: Install dependencies via pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
          version: 7
    - run: pnpm install && cd web && pnpm install
    
    - name: Pnpm test
      run: pnpm test

    - name: Pnpm build
      run: pnpm test